# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: ronaldtest
# "service" is the name of this project. This will also be added to your AWS resource names.
service: servicio-api-starwars

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:PutItem
      Resource:
        - arn:aws:dynamodb:us-east-1:010526281959:table/ElementosStarWars

functions:
  crearElemento:
    handler: manejador.crearElemento
    events:
      - http:
          path: elemento
          method: post

  obtenerElemento:
    handler: manejador.obtenerElemento
    events:
      - http:
          path: elemento/{id}
          method: get
